# Objective: Extract multi-level quantitative features (nodes, segments, branches, network, cell) from the skeletonized network to achieve comprehensive characterization of the cytoskeleton network
# Inputs:
    # Skeleton network: NetworkX graph generated by CytoskeletonNetworkAnalyzer (contains node and edge attributes)
    # Raw image: Used to calculate intensity features (if present)
    # Object mask: Used to calculate spatial distribution features (if present)
# Key design features:
    # Multi-level feature extraction: Supports feature calculation at five levels: nodes, segments, branches, network, and cell
    # Feature classification system: Four main categories of features: morphology, topology, spatial distribution, and intensity
        # Morphology (describes geometric properties of the object itself (size, shape, curvature, etc.));
        # Topology (describes network connection relationships),
        # Spatial distribution (describes position and orientation relationships of the object in space);
        # Intensity (describes fluorescence signal characteristics);
    # Unified calculation method: Intensity features are calculated using a unified method to ensure consistency
    # Physical unit conversion: All features are calculated using physical units (micrometers)
    # Hierarchical feature aggregation: Supports hierarchical feature aggregation from nodes -> segments -> branches -> network -> cell
    # Mapping relationship construction: Automatically builds mapping relationships for nodes-segments-branches-network
    # Dimensionality adaptation: Automatically handles 2D/3D data

import numpy as np
import pandas as pd
import networkx as nx
import matplotlib as mpl

mpl.use('Agg')
from skimage import measure
from sklearn.decomposition import PCA
from .FeatureExtractor_cell import CellFeatureCalculator
from .FeatureExtractor_node import NodeFeatureCalculator
from .FeatureExtractor_segment import SegmentFeatureCalculator
from .FeatureExtractor_branch import BranchFeatureCalculator
from .FeatureExtractor_network import NetworkFeatureCalculator

# Add helper function to calculate polygon area
def polygon_area(vertices):
    """Calculate 2D polygon area (Shoelace formula)"""
    x = vertices[:, 0]
    y = vertices[:, 1]
    return 0.5 * np.abs(np.dot(x, np.roll(y, 1)) - np.dot(y, np.roll(x, 1)))


class FeatureExtractor:
    """
    Responsibility: Receive structured data and calculate quantitative metrics. Does not rely on instances of upstream analyzers.
    """

    def __init__(self, graph, edge_properties, centroids, skeleton,
                 raw_image=None, ridge_image=None, obj_mask=None,
                 voxel_size=(1, 1, 1), params=None, layer_select=None,
                 full_image_mode=False, is_3d=False):
        """
        Initialize feature extractor (Decoupled mode)

        Parameters:
        graph: NetworkX graph object
        edge_properties: Dictionary of edge properties
        centroids: Dictionary of node coordinates
        skeleton: Skeleton image
        raw_image: Raw image
        ridge_image: Ridge-enhanced image
        obj_mask: Object mask
        voxel_size: Voxel size (z, y, x)
        params: Parameter dictionary
        layer_select: List of levels to calculate
        full_image_mode: Full image mode flag
        """
        # 1. Data Injection
        self.graph = graph
        self.edge_properties = edge_properties
        self.centroids = centroids
        self.skeleton = skeleton
        self.raw_image = raw_image
        self.ridge_image = ridge_image
        self.obj_mask = obj_mask
        self.params = params if params else {}
        self.full_image_mode = full_image_mode

        # 2. Basic configuration and property calculation
        self.layer_select = layer_select if layer_select else ['nodes', 'segments', 'branches', 'network', 'cell']

        # Dimensionality judgment: Prioritize using the passed is_3d, otherwise infer based on skeleton dimension
        if is_3d is not None:
            self.is_3d = is_3d
        else:
            self.is_3d = self.skeleton.ndim == 3

        # === Voxel size processing logic: Strictly distinguish 2D/3D ===
        # The passed voxel_size is usually in (z, y, x) format
        vs_arr = np.array(voxel_size, dtype=float)

        if self.is_3d:
            # 3D mode: Needs complete (z, y, x)
            if len(vs_arr) == 2:
                # If only (y, x) is passed, pad with z=1.0
                self.voxel_size = np.insert(vs_arr, 0, 1.0)
            else:
                self.voxel_size = vs_arr
        else:
            # 2D mode: Only needs (y, x), which is also necessary for subsequent coords * voxel_size
            if len(vs_arr) > 2:
                # If (z, y, x) is passed, intercept the last two (y, x)
                self.voxel_size = vs_arr[-2:]
            else:
                self.voxel_size = vs_arr

        # Auxiliary calculation properties (orientation angle, etc.)
        # Now voxel_size dimensions match obj_mask dimensions, calculation will not error
        self.orientation_angle = self._calculate_object_orientation(self.obj_mask)

        # 3. Build topological mapping relationships
        self.node_segment_map = {}
        self.segment_branch_map = {}
        self.node_branch_map = {}
        self.build_mappings()

        # 4. Preprocessing: Check level validity (relies on mapping relationships)
        self._validate_layers()

        # 5. Initialize calculators for each level
        self.node_calculator = NodeFeatureCalculator(self)
        self.segment_calculator = SegmentFeatureCalculator(self)
        self.branch_calculator = BranchFeatureCalculator(self)
        self.network_calculator = NetworkFeatureCalculator(self)
        self.cell_calculator = CellFeatureCalculator(self)

    def _validate_layers(self):
        """Validate and adjust calculation levels"""
        if 'branches' in self.layer_select:
            segment_count = len(self.segment_branch_map)
            branch_count = len(set(self.segment_branch_map.values()))
            if segment_count > 0 and segment_count == branch_count:
                self.layer_select.remove('branches')
                print("Warning: All segments are independent branches, skipping branch-level feature calculation")

        if 'cell' in self.layer_select and (self.obj_mask is None or self.full_image_mode):
            self.layer_select.remove('cell')
            print("Warning: Object mask does not exist or full image mode is active, skipping cell-level feature calculation")

    # ====================== Key Functions ======================
    def build_mappings(self):
        """Build mapping relationships between nodes, segments, and branches (independent of feature calculation order)"""
        # Clear existing mappings
        self.node_segment_map = {}
        self.segment_branch_map = {}
        self.node_branch_map = {}

        # If graph does not exist, return directly
        if not self.graph:
            return

        # Get connected components
        components = list(nx.connected_components(self.graph))

        # Assign ID to each connected component (branch)
        for branch_id, comp in enumerate(components):
            # Create subgraph
            subgraph = self.graph.subgraph(comp)

            # Iterate through all edges of the subgraph
            for u, v in subgraph.edges():
                # Try two possible edge key orders
                edge_key1 = (u, v)
                edge_key2 = (v, u)

                # Check if edge property exists
                if edge_key1 in self.edge_properties:
                    props_list = self.edge_properties[edge_key1]
                elif edge_key2 in self.edge_properties:
                    props_list = self.edge_properties[edge_key2]
                else:
                    continue

                # Assign unique ID to each segment
                for prop_idx, props in enumerate(props_list):
                    # Create unique segment ID - use numeric ID
                    segment_id = len(self.segment_branch_map)  # Use current mapping count as ID

                    # Add segment to branch mapping
                    self.segment_branch_map[segment_id] = branch_id

                    # Add node to segment mapping
                    if u not in self.node_segment_map:
                        self.node_segment_map[u] = []
                    self.node_segment_map[u].append(segment_id)

                    if v not in self.node_segment_map:
                        self.node_segment_map[v] = []
                    self.node_segment_map[v].append(segment_id)

            # Add node to branch mapping
            for node_id in comp:
                self.node_branch_map[node_id] = branch_id

    def _calc_network_features(self):
        """Calculate features for each level, filter parameters according to level selection, and retain feature aggregation"""
        # 1. Calculate basic feature tables
        results = self._calculate_base_features()

        # 2. Feature aggregation
        aggregated = self._aggregate_across_levels(results)  # Method name changed

        # 3. Concatenate full features
        full_features = self._build_full_features(results, aggregated)

        return full_features

    def _calculate_base_features(self):
        """Calculate base features for each level"""
        results = {}

        # Define level processors
        processors = {
            'nodes': (self.node_calculator, 'calculate_node_features'),
            'segments': (self.segment_calculator, 'calculate_segments_features'),
            'branches': (self.branch_calculator, 'calculate_branch_features'),
            'network': (self.network_calculator, 'calculate_network_features'),
            'cell': (self.cell_calculator, 'calculate_cell_features')
        }

        # Execute calculations based on selection
        for layer in self.layer_select:
            calculator, method_name = processors[layer]
            method = getattr(calculator, method_name)
            results[layer] = method()

        # Return empty DataFrame for unselected levels
        for layer in processors:
            if layer not in results:
                results[layer] = pd.DataFrame()

        return results

    def _aggregate_across_levels(self, results):
        """Execute cross-level feature aggregation"""
        aggregated = {
            'segment': pd.DataFrame(),
            'branch': pd.DataFrame(),
            'network': pd.DataFrame()
        }

        # Get base feature tables
        nodes_df = results['nodes']
        segments_df = results['segments']
        branches_df = results['branches']

        # 1. Segment-level aggregated features (aggregated from nodes)
        if not nodes_df.empty and 'segments' in self.layer_select:
            aggregated['segment'] = self._compute_aggregated_features(
                nodes_df,
                group_col='segment_ids',
                prefix='node',
                skip_cols=['node_graph_id', 'node_id', 'z_um', 'y_um', 'x_um', 'branch_id', 'segment_ids']
            )

        # 2. Branch-level aggregated features (aggregated from nodes and segments)
        if 'branches' in self.layer_select:
            branch_agg = pd.DataFrame()

            # Node aggregated features
            if not nodes_df.empty:
                branch_node_agg = self._compute_aggregated_features(
                    nodes_df,
                    group_col='branch_id',
                    prefix='node',
                    skip_cols=['node_id', 'numeric_id', 'z_um', 'y_um', 'x_um', 'segment_ids', 'branch_id']
                )
                branch_agg = branch_node_agg

            # Segment aggregated features
            if not segments_df.empty:
                branch_segment_agg = self._compute_aggregated_features(
                    segments_df,
                    group_col='branch_id',
                    prefix='segment',
                    skip_cols=['segment_id', 'branch_id']
                )

                # Merge node and segment aggregated features
                if not branch_agg.empty:
                    branch_agg = pd.merge(
                        branch_agg,
                        branch_segment_agg,
                        on='branch_id',
                        how='outer'
                    )
                else:
                    branch_agg = branch_segment_agg

            aggregated['branch'] = branch_agg

        # 3. Network-level aggregated features (aggregated from all levels)
        if 'network' in self.layer_select:
            network_agg_list = []

            # Node aggregated features
            if not nodes_df.empty:
                network_node_agg = self._compute_aggregated_features(
                    nodes_df,
                    group_col=None,
                    prefix='node',
                    skip_cols=['node_id', 'numeric_id', 'z_um', 'y_um', 'x_um', 'segment_ids', 'branch_id']
                )
                network_agg_list.append(network_node_agg)

            # Segment aggregated features
            if not segments_df.empty:
                network_segment_agg = self._compute_aggregated_features(
                    segments_df,
                    group_col=None,
                    prefix='segment',
                    skip_cols=['segment_id', 'branch_id']
                )
                network_agg_list.append(network_segment_agg)

            # Branch aggregated features
            if not branches_df.empty:
                network_branch_agg = self._compute_aggregated_features(
                    branches_df,
                    group_col=None,
                    prefix='branch',
                    skip_cols=['branch_id']
                )
                network_agg_list.append(network_branch_agg)

            # Merge all aggregated features
            if network_agg_list:
                aggregated['network'] = pd.concat(network_agg_list, axis=1)

        return aggregated

    def _build_full_features(self, results, aggregated):
        """Build full feature tables"""
        # Get base feature tables
        nodes_df = results['nodes']
        segments_df = results['segments']
        branches_df = results['branches']
        network_df = results['network']
        cell_df = results['cell']

        # 1. Segment-level full features = segment its own features + node aggregated features
        segments_full_df = segments_df
        if not segments_df.empty and not aggregated['segment'].empty:
            segments_full_df = pd.merge(
                segments_df,
                aggregated['segment'],
                left_index=True,
                right_on='segment_ids',
                how='left'
            )

        # 2. Branch-level full features = branch its own features + aggregated features
        branches_full_df = branches_df
        if not branches_df.empty and not aggregated['branch'].empty:
            branches_full_df = pd.merge(
                branches_df,
                aggregated['branch'],
                on='branch_id',
                how='left'
            )

        # 3. Network-level full features = network its own features + all aggregated features
        # Add prefix to network_df
        if not network_df.empty:
            network_df = network_df.add_prefix('network_')
        network_full_df = network_df
        if not network_df.empty and not aggregated['network'].empty:
            network_full_df = pd.merge(
                network_df,
                aggregated['network'],
                how='cross'
            )
        # 4. Cell-level full features = cell its own features + network-level full features
        # Add prefix to cell_df
        if not cell_df.empty:
            cell_df = cell_df.add_prefix('cell_')

        cell_full_df = cell_df
        if not cell_df.empty:
            # Merge network-level full features
            if not network_full_df.empty:
                cell_full_df = pd.merge(
                    cell_full_df,
                    network_full_df,
                    how='cross'
                )

        return {
            'nodes': nodes_df,
            'segments': segments_full_df,
            'branches': branches_full_df,
            'network': network_full_df,
            'cell': cell_full_df
        }

    def get_full_network_report(self):
        """Get the full network report, including cell-level features"""
        results = self._calc_network_features()

        # Create feature report
        feature_report = pd.DataFrame()
        if 'network' in results and not results['network'].empty:
            feature_report = results['network'].copy()

        return {
            'nodes': results['nodes'],
            'segments': results['segments'],
            'branches': results['branches'],
            'network': results['network'],
            'cell': results['cell'],
            'feature_report': feature_report
        }

    def _compute_aggregated_features(self, df, group_col=None, prefix='', skip_cols=None, stats_methods=None):
        """
        Generic feature aggregation function (enhanced version)
        :param df: Input DataFrame
        :param group_col: Group column name (None means aggregate the whole table)
        :param prefix: Feature name prefix
        :param skip_cols: Columns to skip
        :param stats_methods: List of statistical methods, optional values include 'mean', 'std', 'min', 'max', 'sum', 'cv' (coefficient of variation)
        :return: Aggregated feature DataFrame
        """
        if skip_cols is None:
            skip_cols = []

        if stats_methods is None:
            stats_methods = ['mean', 'std']  # Default statistics

        # Only process numeric columns
        numeric_cols = [col for col in df.columns
                        if np.issubdtype(df[col].dtype, np.number)
                        and col not in skip_cols]

        if not numeric_cols:
            return pd.DataFrame()

        # Handle cases where the group column contains multiple values (lists)
        if group_col and group_col in df.columns and df[group_col].apply(lambda x: isinstance(x, list)).any():
            # Create a copy of the exploded data
            exploded_df = df.copy()

            # Explode multi-value columns
            exploded_df = exploded_df.explode(group_col)

            # Group and aggregate using the exploded data
            grouped = exploded_df.groupby(group_col)
        else:
            # Normal grouping
            if group_col:
                grouped = df.groupby(group_col)
            else:
                # Aggregate the whole table
                grouped = df.groupby(lambda x: 0)

        # Define list of statistical functions
        agg_funcs = []
        agg_names = []

        # Add requested statistical methods
        if 'mean' in stats_methods:
            agg_funcs.append('mean')
            agg_names.append('mean')
        if 'std' in stats_methods:
            agg_funcs.append('std')
            agg_names.append('std')
        if 'min' in stats_methods:
            agg_funcs.append('min')
            agg_names.append('min')
        if 'max' in stats_methods:
            agg_funcs.append('max')
            agg_names.append('max')
        if 'sum' in stats_methods:
            agg_funcs.append('sum')
            agg_names.append('sum')
        if 'median' in stats_methods:
            agg_funcs.append('median')
            agg_names.append('median')

        # Add CV (coefficient of variation) statistical method
        if 'cv' in stats_methods:
            def cv_func(x):
                mean = np.mean(x)
                return np.std(x) / mean if mean > 1e-6 else np.nan

            agg_funcs.append(cv_func)
            agg_names.append('cv')

        # If there are no valid statistical methods, return empty DataFrame
        if not agg_funcs:
            return pd.DataFrame()

        # Calculate statistics - use list format of aggregation functions
        agg_df = grouped[numeric_cols].agg(agg_funcs)

        # Flatten column names
        # Create new column name list
        new_columns = []
        for col in numeric_cols:
            for name in agg_names:
                new_columns.append(f"{col}_{name}")

        # Set new column names
        agg_df.columns = new_columns

        # Add prefix
        if prefix:
            agg_df.columns = [f'{prefix}_{col}' for col in agg_df.columns]

        return agg_df.reset_index(drop=True) if group_col is None else agg_df.reset_index()

    def _compute_unified_intensity_features(self, points, is_node=False):
        """
        Unified method to calculate intensity features (using pixel coordinates)
        points: List of all pixel coordinates contained in the object (pixel coordinates)
        is_node: Whether it is a node (single point)
        Returns a dictionary containing 15 intensity features (all positional features use physical coordinates)
        """
        if self.raw_image is None:
            return {k: np.nan for k in [
                'IntegratedIntensity',  # Integrated intensity; quantifies the total fluorescence signal of the object
                'MeanIntensity',  # Mean intensity; quantifies the average fluorescence intensity of the object
                'StdIntensity',  # Intensity standard deviation; quantifies the dispersion of the intensity distribution
                'MaxIntensity',  # Maximum intensity; quantifies the fluorescence intensity of the brightest point
                'MinIntensity',  # Minimum intensity; quantifies the fluorescence intensity of the dimmest point
                'MassDisplacement_um',  # Center of mass displacement (physical units); quantifies the deviation of the intensity distribution from the geometric center
                'LowerQuartileIntensity',  # Lower quartile intensity; quantifies the low end of the intensity distribution
                'MedianIntensity',  # Median intensity; quantifies the middle value of the intensity distribution
                'MADIntensity',  # Median absolute deviation; quantifies the dispersion of the intensity distribution (robust to outliers)
                'UpperQuartileIntensity',  # Upper quartile intensity; quantifies the high end of the intensity distribution
                'Location_CenterMassIntensity_um',  # Intensity-weighted center of mass position (physical coordinates)
                'Location_MaxIntensity_um',  # Maximum intensity point position (physical coordinates)
                'CVIntensity',  # Coefficient of variation (std/mean); quantifies the relative variation of intensity
                'SkewnessIntensity',  # Skewness; quantifies the asymmetry of the intensity distribution. Positive value: right-skewed distribution (tail extends to the right, most values concentrated on the left), negative value: left-skewed distribution (tail extends to the left, most values concentrated on the right), 0: symmetric distribution
                'KurtosisIntensity'  # Kurtosis; quantifies the sharpness/flatness of the intensity distribution. Positive value: leptokurtic distribution (more peaked than normal distribution), negative value: platykurtic distribution (flatter than normal distribution), 0: similar to normal distribution
            ]}

        # Collect intensity values and pixel coordinates for all points
        intensities = []
        voxel_coords = []  # Store pixel coordinates

        for point in points:
            try:
                # Get intensity value based on dimension
                if self.is_3d:
                    z, y, x = map(int, point)
                    intensity = self.raw_image[z, y, x]
                else:
                    # 2D image: only take y and x components
                    if len(point) == 3:  # (z,y,x) format
                        _, y, x = point
                    else:  # (y,x) format
                        y, x = point
                    # Convert to integers to avoid float index errors
                    y, x = int(y), int(x)
                    intensity = self.raw_image[y, x]

                intensities.append(intensity)
                voxel_coords.append(point)  # Store pixel coordinates
            except (IndexError, TypeError):
                continue

        intensities = np.array(intensities)
        n_points = len(intensities)

        # If no valid points, return NaN
        if n_points == 0:
            return {k: np.nan for k in [
                'IntegratedIntensity', 'MeanIntensity', 'StdIntensity',
                'MaxIntensity', 'MinIntensity', 'MassDisplacement_um',
                'LowerQuartileIntensity', 'MedianIntensity', 'MADIntensity',
                'UpperQuartileIntensity', 'Location_CenterMassIntensity_um',
                'Location_MaxIntensity_um', 'CVIntensity',
                'SkewnessIntensity', 'KurtosisIntensity'
            ]}

        # Basic intensity features
        features = {
            'IntegratedIntensity': np.sum(intensities),
            'MeanIntensity': np.mean(intensities),
            'StdIntensity': np.std(intensities),
            'MinIntensity': np.min(intensities),
            'MaxIntensity': np.max(intensities),
        }

        # Quantile features
        features['LowerQuartileIntensity'] = np.percentile(intensities, 25)
        features['MedianIntensity'] = np.median(intensities)
        features['UpperQuartileIntensity'] = np.percentile(intensities, 75)

        # MAD feature (Median Absolute Deviation)
        features['MADIntensity'] = np.median(np.abs(intensities - features['MedianIntensity']))

        # Coefficient of variation (CV)
        if features['MeanIntensity'] > 0:
            features['CVIntensity'] = features['StdIntensity'] / features['MeanIntensity']
        else:
            features['CVIntensity'] = np.nan

        # === New: Calculate Skewness ===
        if n_points >= 3 and features['StdIntensity'] > 0:
            # Use sample skewness formula (Fisher-Pearson coefficient)
            mean_val = features['MeanIntensity']
            std_val = features['StdIntensity']
            # Use unbiased estimate, when n is large (n-1) ≈ n
            if n_points > 1:
                # Sample skewness formula: g1 = (n/((n-1)*(n-2))) * Σ((x_i - mean)/std)^3
                n = n_points
                cubed_deviations = np.sum(((intensities - mean_val) / std_val) ** 3)
                features['SkewnessIntensity'] = (n * cubed_deviations) / ((n - 1) * (n - 2))
            else:
                features['SkewnessIntensity'] = np.nan
        else:
            features['SkewnessIntensity'] = np.nan

        # === New: Calculate Kurtosis ===
        if n_points >= 4 and features['StdIntensity'] > 0:
            # Use sample kurtosis formula (Excess kurtosis, normal distribution is 0)
            mean_val = features['MeanIntensity']
            std_val = features['StdIntensity']
            n = n_points

            # Calculate fourth central moment
            fourth_moment = np.mean((intensities - mean_val) ** 4)

            # Excess kurtosis formula: g2 = (n*(n+1)/((n-1)*(n-2)*(n-3))) * Σ((x_i - mean)/std)^4 - 3*(n-1)^2/((n-2)*(n-3))
            if n > 3:
                # First calculation method: use formula
                term1 = n * (n + 1) / ((n - 1) * (n - 2) * (n - 3))
                fourth_power_sum = np.sum(((intensities - mean_val) / std_val) ** 4)
                term2 = 3 * (n - 1) ** 2 / ((n - 2) * (n - 3))
                features['KurtosisIntensity'] = term1 * fourth_power_sum - term2
            else:
                features['KurtosisIntensity'] = np.nan
        else:
            features['KurtosisIntensity'] = np.nan

        # Maximum intensity position (physical coordinates)
        max_idx = np.argmax(intensities)
        max_point = voxel_coords[max_idx]
        features['Location_MaxIntensity_um'] = tuple(self._to_physical_coordinates(max_point))

        # Intensity-weighted center of mass (physical coordinates)
        total_intensity = features['IntegratedIntensity']
        if total_intensity > 0:
            # Calculate weighted center of mass (pixel coordinates)
            weighted_centroid_voxel = np.zeros(3)
            for i, coord in enumerate(voxel_coords):
                if self.is_3d:
                    coord_arr = np.array(coord)
                else:
                    if len(coord) == 3:  # (z,y,x) format
                        coord_arr = np.array(coord)
                    else:  # (y,x) format
                        coord_arr = np.array([0, coord, coord])
                weighted_centroid_voxel += coord_arr * intensities[i]
            weighted_centroid_voxel /= total_intensity

            # Convert to physical coordinates
            features['Location_CenterMassIntensity_um'] = tuple(
                self._to_physical_coordinates(weighted_centroid_voxel)
            )
        else:
            features['Location_CenterMassIntensity_um'] = self._to_physical_coordinates(
                voxel_coords) if voxel_coords else (np.nan, np.nan, np.nan)

        # Center of mass displacement (physical units)
        if voxel_coords and len(voxel_coords) > 0:
            # Calculate binary center of mass (geometric center of all points)
            if self.is_3d:
                binary_centroid_voxel = np.mean([np.array(p) for p in voxel_coords], axis=0)
            else:
                # 2D image: only take y and x components
                coords_2d = []
                for coord in voxel_coords:
                    if len(coord) == 3:  # (z,y,x) format
                        _, y, x = coord
                        coords_2d.append([y, x])
                    else:  # (y,x) format
                        coords_2d.append(coord)
                binary_centroid_voxel = np.mean(coords_2d, axis=0)
                # Add z dimension
                binary_centroid_voxel = np.array([0, binary_centroid_voxel, binary_centroid_voxel])

            # Convert to physical coordinates
            binary_centroid_phy = self._to_physical_coordinates(binary_centroid_voxel)
            intensity_centroid_phy = features['Location_CenterMassIntensity_um']

            # Calculate distance
            features['MassDisplacement_um'] = np.linalg.norm(
                np.array(binary_centroid_phy) - np.array(intensity_centroid_phy)
            )
        else:
            features['MassDisplacement_um'] = np.nan

        return features

    def _get_value(self, values, index, default=np.nan):
        """Safely get value from list, avoiding index errors"""
        try:
            return values[index] if index < len(values) else default
        except (IndexError, TypeError):
            return default

    # ====================== Shared Methods ======================
    def _calculate_filament_direction(self, path):
        """
        Calculate segment direction vector (physical coordinates)
        :param path: List of segment path points
        :return: Direction vector (unit vector)
        """
        if len(path) < 2:
            return np.zeros(3) if self.is_3d else np.zeros(2)

        start = np.array(self._to_physical_coordinates(path))
        end = np.array(self._to_physical_coordinates(path[-1]))

        vector = end - start
        norm = np.linalg.norm(vector)
        return vector / norm if norm > 1e-6 else vector

    def _compute_oop(self, directions):
        """
        Calculate Orientation Order Parameter (OOP)
        :param directions: List of direction vectors
        :return: OOP value (0-1)
        """
        if len(directions) == 0:
            return np.nan

        # Calculate orientation tensor
        oot_all = np.einsum('ki,kj->kij', directions, directions)
        oot_mean = np.mean(oot_all, axis=0)

        # 3D anisotropy tensor
        n_features = directions.shape
        oot = 1.5 * (oot_mean - np.eye(n_features) / n_features)
        eigenvalues = np.linalg.eigvalsh(oot)
        return np.max(eigenvalues)

    def _calculate_object_orientation(self, obj_mask):
        """Calculate main object orientation (uses PCA for 3D, regionprops for 2D)"""
        if obj_mask is None or np.sum(obj_mask) == 0:
            return 0.0

        if self.is_3d:
            # 3D object uses PCA to calculate main direction
            coords = np.argwhere(obj_mask)
            if len(coords) < 3:
                return 0.0

            # Convert to physical coordinates
            phys_coords = coords * self.voxel_size

            # PCA analysis
            pca = PCA(n_components=3)
            pca.fit(phys_coords)

            # Get main direction vector (first principal component)
            main_direction = pca.components_

            # Calculate azimuth angle (XY plane angle)
            dx, dy, dz = main_direction
            return np.arctan2(dy, dx)  # Return radians
        else:
            # 2D object uses regionprops
            regions = measure.regionprops(obj_mask.astype(int))
            if not regions:
                return 0.0
            return regions.orientation  # Return radians

    def _to_physical_coordinates(self, input_data):
        """Coordinate conversion (migrated from Analyzer)"""
        if isinstance(input_data, (tuple, list, np.ndarray)) and not isinstance(input_data,
                                                                                (tuple, list, np.ndarray)):
            return self._convert_single_point(input_data)
        return [self._convert_single_point(point) for point in input_data]

    def _convert_single_point(self, point):
        """Single point coordinate conversion"""
        if len(point) == 3:
            z, y, x = point
            if self.is_3d:
                return (z * self.voxel_size, y * self.voxel_size, x * self.voxel_size)
            else:
                return (0.0, y * self.voxel_size, x * self.voxel_size)
        elif len(point) == 2:
            y, x = point
            return (0.0, y * self.voxel_size, x * self.voxel_size)
        return (0.0, 0.0, 0.0)

    def _calculate_physical_path_length(self, physical_path):
        """Calculate physical path length"""
        if len(physical_path) < 2: return 0.0
        total_length = 0.0
        for i in range(1, len(physical_path)):
            total_length += self._calculate_physical_distance(physical_path[i - 1], physical_path[i])
        return total_length

    def _calculate_physical_distance(self, pos1, pos2):
        """Calculate physical distance"""
        # Note: assumes pos1, pos2 are already physical coordinates, or need internal conversion
        # If input is pixel coordinates:
        pos1_phy = self._to_physical_coordinates(pos1) if not isinstance(pos1, tuple) else pos1
        pos2_phy = self._to_physical_coordinates(pos2) if not isinstance(pos2, tuple) else pos2

        # For simplicity, assume input is already physical coordinates (based on original SegmentFeatureCalculator calling logic)
        # If original logic passed list/array, directly calculate Euclidean distance here
        p1 = np.array(pos1)
        p2 = np.array(pos2)
        return np.linalg.norm(p1 - p2)

'''
**Overall Workflow**
1. **Initialization and Data Preparation**
   - Receives main analyzer instance (contains skeleton network, raw image, object mask, etc.)
   - Initializes mapping dictionaries (node-segment-branch)

2. **Build Mapping Relationships**
   - `build_mappings`: Builds mapping relationships between nodes, segments, and branches to provide a basis for hierarchical feature aggregation

3. **Multi-level Feature Calculation**
   - **Node Features**: Calculate morphology, topology, spatial distribution, and intensity features for each node
   - **Segment Features**: Calculate morphology (length, width, curvature), topology (connections), spatial distribution (orientation), and intensity features for each segment
   - **Branch Features**: Identify branch structures (connected components), calculate morphology, topology, spatial distribution, and intensity features for branches
   - **Network Features**: Calculate morphology, topology, spatial distribution, and intensity features for the entire network
   - **Cell Features**: Calculate cell-level morphology, spatial distribution, and intensity features  # New cell feature calculation

4. **Feature Aggregation**
   - Uses `_compute_aggregated_features` method to aggregate lower-level features to higher levels:
     - Node features -> Segment features
     - Node + Segment features -> Branch features
     - All level features -> Network features
     - Network features -> Cell features  # New cell feature aggregation

5. **Generate Full Report**
   - `get_full_network_report`: Generates a dictionary containing all level features and aggregated feature reports

**Core Feature Calculations**
- **Morphology Features**: Length, width, curvature, area/volume, compactness, etc.
- **Topology Features**: Node degree, betweenness centrality, clustering coefficient, global efficiency, branching ratio, etc.
- **Spatial Distribution Features**: Position coordinates, orientation angles, anisotropy, orientation entropy, etc.
- **Intensity Features**: Mean intensity, intensity standard deviation, intensity distribution (quantiles), center of mass displacement, etc.

**Output**
- Node feature table (non-aggregated)
- Segment feature table (includes aggregated node features)
- Branch feature table (includes aggregated node and segment features)
- Network feature table (includes aggregated features from all levels)
- Cell feature table (includes aggregated network features)  # New cell feature table
- Network feature report (statistical summary of network-level features)
'''